services:
  hashservice:
    image: ${DOCKER_REGISTRY-}hashservice
    build:
      context: .
      dockerfile: Services/HashService/Dockerfile
    container_name: hashservice
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "5001:80"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # RabbitMQ Protocol
      - "15672:15672" # Management Dashboard
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  postservice:
    image: ${DOCKER_REGISTRY-}postservice
    build:
      context: .
      dockerfile: Services/PostService/Dockerfile
    container_name: postservice
    depends_on:
      - rabbitmq
    ports:
      - "5000:80"
    networks:
      - app-network

networks:
  app-network: 
    driver: bridge


