version: '3.8'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Backend/ApiGateway/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - hashservice
      - postservice

  hashservice:
    image: ${DOCKER_REGISTRY-}hashservice
    build:
      context: .
      dockerfile: Backend/HashService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - redis

  postservice:
    image: ${DOCKER_REGISTRY-}postservice
    build:
      context: .
      dockerfile: Backend/PostService/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - mongodb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"