services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Services/APIGateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASS: ${RABBITMQ_PASS}
        ASPNETCORE_URLS: "http://0.0.0.0:8080"
        ConnectionStrings__rabbitmq: "host=rabbitmq:5672;username=${RABBITMQ_USER};password=${RABBITMQ_PASS};publisherConfirms=true"
    # networks:
    #   - overlay-network
    depends_on:
      - rabbitmq
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"  # RabbitMQ Protocol
      - "15672:15672"  # UI
    # networks:
    #   - overlay-network
    env_file:
      - .env

# networks:
#   overlay-network:
#     driver: overlay
