global:
  scrape_interval: 5s  # Частота сбора метрик (каждые 5 секунд)

scrape_configs:
  - job_name: 'api_gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apigateway:8080']

  - job_name: 'node_exporter'  # Системные метрики CPU, RAM
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:15692']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']